version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "postback:1:1"
      #LOG4J_LOGGER_KAFKA: DEBUG
      #LOG4J_LOGGER_ORG_APACHE_KAFKA: DEBUG
      #LOG4J_LOGGER_KAFKA_REQUEST_LOGGER: "DEBUG, requestAppender"
      #LOG4J_ADDITIVITY_KAFKA_REQUEST_LOGGER: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_HOSTNAME_PORT: "kafka:9092"
      KAFKA_POSTBACK_TOPIC: postback
  deliver:
    build:
      context: ./deliver
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - ingest
    environment:
      KAFKA_HOSTNAME_PORT: "kafka:9092"
      KAFKA_POSTBACK_TOPIC: postback
